# ETH Analysis System Configuration

system:
  name: "ETH Analysis System"
  version: "1.0.0"
  timezone: "UTC"

telegram:
  # Channels will be loaded from .env file
  # Additional channel settings
  parse_settings:
    messages_limit: 1000
    days_back: 30
    parse_media: false
    parse_reactions: true
    retry_attempts: 3
    retry_delay: 5  # seconds
  
  # Rate limiting
  rate_limit:
    max_requests_per_minute: 20
    flood_wait_threshold: 60  # seconds

analysis:
  # Technical analysis settings
  technical:
    indicators:
      - name: "SMA"
        periods: [20, 50, 200]
      - name: "EMA"
        periods: [12, 26]
      - name: "RSI"
        period: 14
      - name: "MACD"
        fast: 12
        slow: 26
        signal: 9
      - name: "Bollinger Bands"
        period: 20
        std_dev: 2
      - name: "ATR"
        period: 14
    
    patterns:
      - "head_and_shoulders"
      - "double_top"
      - "double_bottom"
      - "triangle"
      - "flag"
      - "wedge"
    
    support_resistance:
      lookback_periods: [20, 50, 100]
      strength_threshold: 3
  
  # News analysis settings
  news:
    relevance_threshold: 0.7
    sentiment_weights:
      positive:
        partnership: 3
        upgrade: 3
        adoption: 3
        bullish: 2
        growth: 2
        institutional: 3
        etf: 3
      negative:
        hack: -3
        scam: -3
        crash: -3
        regulation: -2
        ban: -3
        lawsuit: -2
        vulnerability: -3
    
    impact_levels:
      high: 5.0
      medium: 2.0
      low: 0.5

model:
  # Data preparation
  data:
    sequence_length: 60
    train_split: 0.7
    validation_split: 0.15
    test_split: 0.15
    scaling_method: "minmax"  # minmax or standard
  
  # Architecture
  architecture:
    type: "advanced_gru"  # lightweight_gru or advanced_gru
    technical_lstm:
      hidden_size: 128
      num_layers: 3
      dropout: 0.3
      bidirectional: true
    
    news_encoder:
      hidden_sizes: [64, 32]
      dropout: 0.3
    
    attention:
      num_heads: 8
      dropout: 0.2
    
    fusion_layer:
      hidden_sizes: [256, 128, 64]
      dropout: 0.3
  
  # Training
  training:
    epochs: 50
    batch_size: 32
    learning_rate: 0.001
    optimizer: "AdamW"
    weight_decay: 0.00001
    
    scheduler:
      type: "ReduceLROnPlateau"
      factor: 0.5
      patience: 5
      min_lr: 0.000001
    
    early_stopping:
      patience: 10
      min_delta: 0.0001
    
    loss_function: "huber"  # mse, mae, or huber

# Prediction settings
prediction:
  horizon_days: 7
  confidence_intervals: true
  monte_carlo_iterations: 10
  
  ensemble:
    enabled: false
    models: ["gru", "lstm", "transformer"]
    weights: [0.4, 0.3, 0.3]

# Output settings
output:
  reports:
    format: "json"  # json, csv, or html
    include_raw_data: false
    compression: true
  
  visualizations:
    theme: "plotly_dark"
    save_format: "html"  # html, png, or svg
    interactive: true
    
    charts:
      - type: "candlestick"
        indicators: ["SMA_20", "SMA_50", "BB"]
      - type: "volume"
        color_by_direction: true
      - type: "rsi"
        overbought: 70
        oversold: 30
      - type: "macd"
        show_histogram: true
  
  notifications:
    triggers:
      - event: "high_impact_news"
        threshold: 5.0
      - event: "pattern_detected"
        patterns: ["head_and_shoulders", "double_top"]
      - event: "price_prediction"
        change_threshold: 5.0  # percentage
      - event: "strong_signal"
        confidence_threshold: 0.8

# Performance optimizations
performance:
  cache:
    enabled: true
    backend: "redis"  # memory or redis
    ttl: 3600  # seconds
    
  parallel_processing:
    enabled: true
    max_workers: 4
    
  gpu:
    enabled: true
    device: "cuda:0"  # cuda:0, cuda:1, or cpu

# Logging configuration
logging:
  level: "INFO"  # DEBUG, INFO, WARNING, ERROR
  format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"
  
  handlers:
    console:
      enabled: true
      colored: true
    
    file:
      enabled: true
      filename: "eth_analysis.log"
      max_bytes: 10485760  # 10MB
      backup_count: 5
    
    remote:
      enabled: false
      endpoint: "https://log-aggregator.example.com"

# Database settings
database:
  # Connection string loaded from .env
  pool_size: 10
  max_overflow: 20
  pool_timeout: 30
  
  tables:
    news: "eth_news"
    prices: "eth_prices"
    predictions: "eth_predictions"
    signals: "eth_signals"

# API configuration (if serving predictions)
api:
  title: "ETH Analysis API"
  description: "Real-time ETH price analysis and predictions"
  version: "1.0.0"
  
  cors:
    enabled: true
    origins: ["http://localhost:3000", "https://yourdomain.com"]
    
  rate_limit:
    enabled: true
    requests_per_minute: 60
    
  authentication:
    enabled: false
    type: "bearer"  # bearer or api_key